// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Counter: typeof import('./src/components/Counter.vue')['default']
    Hello: typeof import('./src/components/Hello.vue')['default']
    IxButton: typeof import('@idux/components/button')['IxButton']
    IxForm: typeof import('@idux/components/form')['IxForm']
    IxFormItem: typeof import('@idux/components/form')['IxFormItem']
    IxInput: typeof import('@idux/components/input')['IxInput']
    IxSpace: typeof import('@idux/components/space')['IxSpace']
  }
}

export { }
